using Data;
using Data.Models;
using Infrastructure.DTOs;
using Microsoft.EntityFrameworkCore;
using Repositories.IRepositories;

namespace Repositories.Repositories
{
	public sealed class AnalyticsRepository : IAnalyticsRepository
	{
		private readonly DataContext _context;

		public AnalyticsRepository(DataContext context)
		{
			_context = context;
		}

		public async Task<DashboardAnalyticsDto> GetDashboardAnalyticsAsync(CancellationToken ct = default)
		{
			var dto = new DashboardAnalyticsDto();

			// Scaffold group counts
			var groups = await _context.ScaffoldGroups
				.Select(sg => new { sg.IsSimulated, sg.IsPublic })
				.ToListAsync(ct);

			dto.TotalScaffoldGroups = groups.Count;
			dto.SimulatedGroupCount = groups.Count(g => g.IsSimulated);
			dto.RealGroupCount = groups.Count(g => !g.IsSimulated);
			dto.PublicCount = groups.Count(g => g.IsPublic);
			dto.PrivateCount = groups.Count(g => !g.IsPublic);

			// Scaffold counts (total + simulated/real via ScaffoldGroup)
			var scaffoldCounts = await _context.Scaffolds
				.GroupBy(s => s.ScaffoldGroup.IsSimulated)
				.Select(g => new { IsSimulated = g.Key, Count = g.Count() })
				.ToListAsync(ct);

			dto.TotalScaffolds = scaffoldCounts.Sum(s => s.Count);
			dto.SimulatedScaffoldCount = scaffoldCounts.Where(s => s.IsSimulated).Sum(s => s.Count);
			dto.RealScaffoldCount = scaffoldCounts.Where(s => !s.IsSimulated).Sum(s => s.Count);

			// Tag distributions grouped by ReferenceProperty, with simulated/real breakdown
			var tagCounts = await _context.ScaffoldTags
				.Where(st => st.Tag.IsAutoGenerated)
				.GroupBy(st => new { st.Tag.ReferenceProperty, st.Tag.Name })
				.Select(g => new
				{
					ReferenceProperty = g.Key.ReferenceProperty ?? "other",
					TagName = g.Key.Name,
					Count = g.Count(),
					SimulatedCount = g.Sum(st => st.Scaffold.ScaffoldGroup.IsSimulated ? 1 : 0),
					RealCount = g.Sum(st => st.Scaffold.ScaffoldGroup.IsSimulated ? 0 : 1)
				})
				.ToListAsync(ct);

			dto.TagDistributions = tagCounts
				.GroupBy(t => t.ReferenceProperty)
				.ToDictionary(
					g => g.Key,
					g => g.Select(t => new CategoryCountDto
						{
							Name = t.TagName,
							Count = t.Count,
							SimulatedCount = t.SimulatedCount,
							RealCount = t.RealCount
						})
						.OrderByDescending(c => c.Count)
						.ToList()
				);

			// Packing configuration distribution with simulated/real breakdown
			var packingRaw = await _context.InputGroups
				.GroupBy(ig => ig.PackingConfiguration)
				.Select(g => new
				{
					Key = g.Key,
					Count = g.Count(),
					SimulatedCount = g.Sum(ig => ig.ScaffoldGroup.IsSimulated ? 1 : 0),
					RealCount = g.Sum(ig => ig.ScaffoldGroup.IsSimulated ? 0 : 1)
				})
				.OrderByDescending(g => g.Count)
				.ToListAsync(ct);

			dto.PackingConfigurationDistribution = packingRaw.Select(p => new CategoryCountDto
			{
				Name = p.Key.ToString(),
				Count = p.Count,
				SimulatedCount = p.SimulatedCount,
				RealCount = p.RealCount
			}).ToList();

			// Container shape distribution
			dto.ContainerShapeDistribution = await _context.InputGroups
				.Where(ig => ig.ContainerShape != null)
				.GroupBy(ig => ig.ContainerShape!)
				.Select(g => new CategoryCountDto
				{
					Name = g.Key,
					Count = g.Count()
				})
				.OrderByDescending(c => c.Count)
				.ToListAsync(ct);

			// Particle size bins with simulated/real breakdown
			var sizeRows = await _context.ParticlePropertyGroups
				.Select(p => new { p.MeanSize, p.InputGroup.ScaffoldGroup.IsSimulated })
				.ToListAsync(ct);

			var bins = new (string Label, double Min, double Max)[]
			{
				("0–50 μm",    0,    50),
				("50–100 μm",  50,   100),
				("100–200 μm", 100,  200),
				("200–500 μm", 200,  500),
				("500–1000 μm", 500, 1000),
				("1000+ μm",   1000, double.MaxValue)
			};

			dto.ParticleSizeBins = bins.Select(b =>
			{
				var inBin = sizeRows.Where(s => s.MeanSize >= b.Min && s.MeanSize < b.Max).ToList();
				return new SizeBinDto
				{
					Label = b.Label,
					MinSize = b.Min,
					MaxSize = b.Max == double.MaxValue ? -1 : b.Max,
					Count = inBin.Count,
					SimulatedCount = inBin.Count(s => s.IsSimulated),
					RealCount = inBin.Count(s => !s.IsSimulated)
				};
			}).ToList();

			// Uploads over time (by year-month)
			dto.UploadsOverTime = await _context.ScaffoldGroups
				.GroupBy(sg => new { sg.CreatedAt.Year, sg.CreatedAt.Month })
				.OrderBy(g => g.Key.Year).ThenBy(g => g.Key.Month)
				.Select(g => new TimeSeriesPointDto
				{
					Period = g.Key.Year + "-" + g.Key.Month.ToString("D2"),
					Count = g.Count()
				})
				.ToListAsync(ct);

			// Downloads over time (by year-month)
			dto.DownloadsOverTime = await _context.Downloads
				.GroupBy(d => new { d.CreatedAt.Year, d.CreatedAt.Month })
				.OrderBy(g => g.Key.Year).ThenBy(g => g.Key.Month)
				.Select(g => new TimeSeriesPointDto
				{
					Period = g.Key.Year + "-" + g.Key.Month.ToString("D2"),
					Count = g.Count()
				})
				.ToListAsync(ct);

			return dto;
		}
	}
}
