using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Repositories.IRepositories;
using Data;
using Data.Models;

namespace Repositories.Repositories
{
	public class TagRepository : ITagRepository
	{
		private readonly DataContext _context;

		public TagRepository(DataContext context)
		{
			_context = context;
		}

		public bool HasChanges()
		{
			return _context.ChangeTracker.HasChanges();
		}
		public void Add(Tag tag)
		{
			_context.Tags.Add(tag);
		}
		public async Task<Tag?> GetTagById(int id)
		{
			return await _context.Tags.FindAsync(id);
		}
		public async Task<Tag?> GetTagByName(string name)
		{
			return await _context.Tags.Where(t => t.Name == name).FirstOrDefaultAsync();
		}
		public async Task<ICollection<Tag>> GetAutoGeneratedTags()
		{
			return await _context.Tags.Where(t => t.IsAutoGenerated == true).OrderBy(t => t.Name).ToListAsync();
		}

	}
}


