version: '3.8'

services:
  db:
    image: postgres:17
    container_name: lovamap_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_preprod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./GatewayBackend
      args:
        ENVIRONMENT: preproduction
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
        - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  nginx:
    build:
      context: ./GatewayUI/react-ui
      dockerfile: Dockerfile
      args:
        NODE_ENV: preproduction
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.preproduction.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_preprod:
