import { observer } from "mobx-react-lite";
import React, { useEffect, useState, useRef, useCallback } from "react";
import { useStore } from "../../app/stores/store";
import { GroupedTags, Tag, displayNameMap } from "../../app/models/tag";
import { FaCaretDown } from "react-icons/fa";
import { useOnClickOutside } from "../../app/common/hooks/useOnClickOutside";

interface ScaffoldGroupFiltersProps {
	condensed?: boolean;
	allFiltersVisible?: boolean;
	setIsLoading: (loading: boolean) => void;
	selectedTags: { [key: string]: Tag[] };
	setSelectedTags: React.Dispatch<React.SetStateAction<{ [key: string]: Tag[] }>>;
	selectedParticleSizeIds: number[];
	setSelectedParticleSizeIds: React.Dispatch<React.SetStateAction<number[]>>;
	isSimulated: boolean | null;
	setIsSimulated: React.Dispatch<React.SetStateAction<boolean | null>>;
}

const ScaffoldGroupFilters: React.FC<ScaffoldGroupFiltersProps> = ({
    allFiltersVisible = false,
    selectedTags = {},
    setSelectedTags,
    selectedParticleSizeIds = [],
    setSelectedParticleSizeIds,
    isSimulated,
    setIsSimulated
}) => {
    const {resourceStore} = useStore();
	const {getAutogeneratedTags} = resourceStore;

	const [groupedTags, setGroupedTags] = useState<GroupedTags>({});
    const [particleSizes, setParticleSizes] = useState<{id: number, label: string}[]>([]);
    const [filtersVisible, setFiltersVisible] = useState<boolean>(allFiltersVisible);
    const containerRef = useRef<HTMLDivElement | null>(null);

    const closeFilters = useCallback(() => {
        if (filtersVisible) setFiltersVisible(false);
    }, [filtersVisible]);

    useOnClickOutside(containerRef, closeFilters);

    useEffect(() => {
        const onKey = (e: KeyboardEvent) => {
            if (e.key === "Escape") setFiltersVisible(false);
        };
        window.addEventListener("keydown", onKey);
        return () => window.removeEventListener("keydown", onKey);
    }, []);

	useEffect(() => {
        getAutogeneratedTags().then(fetchedTags => {
            if (fetchedTags) {
                const groups = fetchedTags.reduce<GroupedTags>((acc, tag) => {
                    const groupKey = tag.referenceProperty;
                    if (displayNameMap[groupKey]) {
                        acc[groupKey] = acc[groupKey] || [];
                        acc[groupKey].push(tag);
                    }
                    return acc;
                }, {});
                setGroupedTags(groups);
            }
        }).catch(error => {
            console.error("Error fetching tags:", error);
        });
    }, [getAutogeneratedTags]);

    useEffect(() => {
        const sizes: {id: number, label: string}[] = [];
        for (let i = 40; i <= 200; i += 10) {
            sizes.push({ id: i, label: `${i}um` });
        }
        setParticleSizes(sizes);
    }, []);

	const handleSelectTag = (groupKey: string, tag: Tag) => {
        setSelectedTags(prev => {
            const updatedTags = { ...prev };
            if (updatedTags[groupKey]?.find(t => t.id === tag.id)) {
                updatedTags[groupKey] = updatedTags[groupKey].filter(t => t.id !== tag.id);
            } else {
                updatedTags[groupKey] = updatedTags[groupKey] ? [...updatedTags[groupKey], tag] : [tag];
            }
            return updatedTags;
        });
    };

    const handleParticleSizeSelect = (id: number) => {
        if (selectedParticleSizeIds.includes(id)) {
            setSelectedParticleSizeIds(prev => prev.filter(s => s !== id));
        } else {
            setSelectedParticleSizeIds(prev => [...prev, id]);
        }
    };

    const handleSourceToggle = (source: "simulated" | "microscopy") => {
        const simChecked = isSimulated === null || isSimulated === true;
        const micChecked = isSimulated === null || isSimulated === false;
        const newSim = source === "simulated" ? !simChecked : simChecked;
        const newMic = source === "microscopy" ? !micChecked : micChecked;

        if (newSim && newMic) setIsSimulated(null);
        else if (newSim) setIsSimulated(true);
        else if (newMic) setIsSimulated(false);
        else setIsSimulated(null);
    };

    return (
        <div className="relative w-full rounded-xl" ref={containerRef}>
            {/* Toggle Button */}
            <div
                className="flex items-center text-left cursor-pointer hover:underline"
                onClick={() => setFiltersVisible(prev => !prev)}
            >
                <p className="text-gray-700 font-semibold mr-1">Filters</p>
                <FaCaretDown className={`transition-transform duration-300 ${filtersVisible ? 'rotate-0' : '-rotate-90'}`} />
            </div>

            {/* Dropdown Panel */}
            {filtersVisible && (
                <div className="absolute mt-2 left-0 w-full bg-white border-b border-gray-300 rounded-xl shadow-md z-50 p-4 max-h-[500px] overflow-y-auto">
                    {/* Source */}
                    <div className="mb-4">
                        <h4 className="text-sm font-semibold text-gray-600 mb-2">Source</h4>
                        <div className="grid grid-cols-3 md:grid-cols-5 lg:grid-cols-6 gap-x-4 gap-y-1">
                            <label className="flex items-center space-x-2 cursor-pointer">
                                <input
                                    type="checkbox"
                                    checked={isSimulated === null || isSimulated === true}
                                    onChange={() => handleSourceToggle("simulated")}
                                    className="accent-link-50"
                                />
                                <span className="text-sm text-gray-700">Simulated</span>
                            </label>
                            <label className="flex items-center space-x-2 cursor-pointer">
                                <input
                                    type="checkbox"
                                    checked={isSimulated === null || isSimulated === false}
                                    onChange={() => handleSourceToggle("microscopy")}
                                    className="accent-link-50"
                                />
                                <span className="text-sm text-gray-700">Microscopy</span>
                            </label>
                        </div>
                    </div>

                    {/* Particle Diameter — column-first so values read top-to-bottom */}
                    <div className="mb-4">
                        <h4 className="text-sm font-semibold text-gray-600 mb-2">Particle Diameter</h4>
                        <div className="grid grid-flow-col grid-rows-6 sm:grid-rows-4 lg:grid-rows-3 gap-x-4 gap-y-1">
                            {particleSizes.map(size => (
                                <label key={size.id} className="flex items-center space-x-2 cursor-pointer">
                                    <input
                                        type="checkbox"
                                        checked={selectedParticleSizeIds.includes(size.id)}
                                        onChange={() => handleParticleSizeSelect(size.id)}
                                        className="accent-link-50"
                                    />
                                    <span className="text-sm text-gray-700">{size.label}</span>
                                </label>
                            ))}
                        </div>
                    </div>

                    {/* Tag Groups */}
                    {Object.entries(groupedTags).map(([key, tags]) => (
                        <div key={key} className="mb-4">
                            <h4 className="text-sm font-semibold text-gray-600 mb-2">
                                {displayNameMap[key] || key}
                            </h4>
                            <div className="grid grid-cols-3 md:grid-cols-5 lg:grid-cols-6 gap-x-4 gap-y-1">
                                {tags.map(tag => {
                                    const checked = selectedTags[key]?.some(t => t.id === tag.id) ?? false;
                                    return (
                                        <label key={tag.id} className="flex items-center space-x-2 cursor-pointer">
                                            <input
                                                type="checkbox"
                                                checked={checked}
                                                onChange={() => handleSelectTag(key, tag)}
                                                className="accent-link-50"
                                            />
                                            <span className="text-sm text-gray-700">{tag.name}</span>
                                        </label>
                                    );
                                })}
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}

export default observer(ScaffoldGroupFilters);
