using System.Collections.Generic;
using System.Threading.Tasks;
using Data.Models;

namespace Repositories.IRepositories
{
    public interface ITagRepository
    {
		bool HasChanges();
		void Add(Tag tag);		
		Task<Tag?> GetTagById(int id);
		Task<Tag?> GetTagByName(string name);
		Task<ICollection<Tag>> GetAutoGeneratedTags();
	}
}