using System.Collections.Generic;
using System.Threading.Tasks;
using Data.Models;

namespace Repositories.IRepositories
{
    public interface ITagRepository
    {
		bool HasChanges();
		void Add(Tag tag);		
		Task<Tag?> GetTagById(int id);
		Task<List<Tag>> GetTagsByIds(ICollection<int> ids);
		Task<Tag?> GetTagByName(string name);
		Task<List<int>> GetAutogeneratedTagIdsFromNames(ICollection<string> names);
		Task<ICollection<Tag>> GetAutoGeneratedTags();
		Task<Dictionary<int, List<string>>> GetTagNamesForScaffoldGroups(IEnumerable<int> scaffoldGroupIds, string userId);
	}
}