
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Data;
using Data.Models;
using Repositories.IRepositories;
using Infrastructure.DTOs;
using Infrastructure.IHelpers;
using Services.IServices;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using CloudinaryDotNet;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;
using Microsoft.EntityFrameworkCore;

namespace Services.Services
{	public class ScaffoldGroupService : IScaffoldGroupService
	{
		private readonly DataContext _context;
		private readonly IModelMapper _modelMapper;
		private readonly IUserAuthHelper _userAuthHelper;
		private readonly IScaffoldGroupMetadataService _metadataService;
		private readonly IScaffoldGroupRepository _scaffoldGroupRepository;
		private readonly IDescriptorService _descriptorService;
		private readonly IDownloadService _downloadService;
		private readonly IDomainService _domainService;
		private readonly ITagService _tagService;
		private readonly IImageService _imageService;
		private readonly ILogger<ScaffoldGroupService> _logger;

		public ScaffoldGroupService(DataContext context, IModelMapper modelMapper, 
			IScaffoldGroupMetadataService metadataService, IScaffoldGroupRepository scaffoldGroupRepository, 
			IDescriptorService descriptorService, IDownloadService downloadService, ITagService tagService, 
			IUserAuthHelper userAuthHelper, IImageService imageService, IDomainService domainService,
			 ILogger<ScaffoldGroupService> logger)
		{
			_context = context;
			_modelMapper = modelMapper;
			_userAuthHelper = userAuthHelper;
			_metadataService = metadataService;
			_scaffoldGroupRepository = scaffoldGroupRepository;
			_descriptorService = descriptorService;
			_imageService = imageService;
			_downloadService = downloadService;
			_tagService = tagService;
			_domainService = domainService;
			_logger = logger;
		}

		public async Task<List<int>> GetAllIds()
		{
			return await _scaffoldGroupRepository.GetAllIds();
		}

		public async Task<int> GetRandomScaffoldGroupId()
		{
			return await _scaffoldGroupRepository.GetRandomScaffoldGroupId();
		}

		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupBaseDto? CreatedScaffoldGroup)> CreateScaffoldGroup(ScaffoldGroupToCreateDto scaffoldGroupToCreate, string? userId)
		{
			var (succeeded, errorMessage, createdScaffoldGroups) = await CreateScaffoldGroups([scaffoldGroupToCreate], userId);

			return (succeeded, errorMessage, createdScaffoldGroups?.FirstOrDefault());
		}

		public async Task<(bool Succeeded, string ErrorMessage, IEnumerable<ScaffoldGroupBaseDto>? CreatedScaffoldGroups)> CreateScaffoldGroups(IEnumerable<ScaffoldGroupToCreateDto> scaffoldGroupsToCreate, string? userId)
		{
			try
			{
				var pendingGroups = new List<(ScaffoldGroup group, List<string> tagNames, string uploaderId)>();

				foreach (var dto in scaffoldGroupsToCreate)
				{
					NormalizeInputGroup(dto);
					EnsureSizeDistribution(dto);
					NormalizeParticleProperties(dto);

					var isAdmin = false;
					if (!string.IsNullOrWhiteSpace(userId))
					{
						isAdmin = await _userAuthHelper.IsInRole(userId, "administrator");
						dto.UploaderId = userId;
					}

					var scaffoldGroup = await _modelMapper.MapToScaffoldGroup(dto);

					if (scaffoldGroup.UploaderId != null && isAdmin == true)
					{
						scaffoldGroup.IsPublic = true;
					}

					if (scaffoldGroup.UploaderId == null)
					{
						var uploader = await _userAuthHelper.GetFirstUserByRoleAsync("administrator");
						if (uploader != null)
						{
							scaffoldGroup.Uploader = uploader;  // Attach the uploader object
							scaffoldGroup.UploaderId = uploader.Id;  // Ensure the ID is set
							scaffoldGroup.IsPublic = true;
						}
					}

					var autogeneratedTags = await _tagService.GetAutogeneratedTagsForScaffold(scaffoldGroup);
					var tagNames = autogeneratedTags.Select(tag => tag.Tag.Name).ToList();

					foreach (var scaffold in scaffoldGroup.Scaffolds)
					{
						scaffold.ScaffoldTags = autogeneratedTags.ToList();
					}

					_scaffoldGroupRepository.Add(scaffoldGroup);
					pendingGroups.Add((scaffoldGroup, tagNames, userId ?? scaffoldGroup.UploaderId!));
				}

				// SaveChanges FIRST so entity IDs are populated
				await _context.SaveChangesAsync();

				// Now map to DTOs — IDs are available
				var createdScaffoldGroups = pendingGroups.Select(entry =>
					_modelMapper.MapToScaffoldGroupSummaryDto(entry.group, [], entry.tagNames, entry.uploaderId)
				).Cast<ScaffoldGroupBaseDto>().ToList();

				return (true, "", createdScaffoldGroups);
			}
			catch (ArgumentException ex)
			{
				_logger.LogWarning(ex, "Invalid scaffold group payload");
				return (false, ex.Message, null);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to create scaffold groups");
				return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupSummaryDto? UpdatedScaffoldGroup)> AppendScaffoldsToGroup(
			int scaffoldGroupId,
			ScaffoldGroupToCreateDto scaffoldsToAppend,
			string userId)
		{
			try
			{
				if (scaffoldsToAppend.Scaffolds == null || scaffoldsToAppend.Scaffolds.Count == 0)
					return (false, "No scaffolds provided.", null);

				NormalizeInputGroup(scaffoldsToAppend);
				EnsureSizeDistribution(scaffoldsToAppend);
				NormalizeParticleProperties(scaffoldsToAppend);

				var scaffoldGroup = await _scaffoldGroupRepository.Get(scaffoldGroupId);
				if (scaffoldGroup == null)
					return (false, "ScaffoldGroupNotFound", null);

				var isAdmin = await _userAuthHelper.IsInRole(userId, "administrator");
				if (scaffoldGroup.UploaderId != userId && !isAdmin)
					return (false, "Unauthorized", null);

				if (scaffoldGroup.InputGroup == null)
					return (false, "Existing scaffold group is missing input-group metadata.", null);

				if (scaffoldGroup.IsSimulated != scaffoldsToAppend.IsSimulated)
					return (false, "Incoming descriptor does not match the target scaffold group's simulation setting.", null);

				if (!AreInputGroupsCompatible(scaffoldGroup.InputGroup, scaffoldsToAppend.InputGroup))
					return (false, "Incoming descriptor inputGroup does not match the target scaffold group's existing inputGroup.", null);

				var autogeneratedTags = await _tagService.GetAutogeneratedTagsForScaffold(scaffoldGroup);
				var nextReplicateNumber = scaffoldGroup.Scaffolds.Count == 0
					? 1
					: scaffoldGroup.Scaffolds.Max(s => s.ReplicateNumber) + 1;

				foreach (var scaffoldDto in scaffoldsToAppend.Scaffolds)
				{
					var scaffold = await _modelMapper.MapToScaffold(scaffoldDto, nextReplicateNumber++);
					scaffold.ScaffoldGroup = scaffoldGroup;
					scaffold.ScaffoldGroupId = scaffoldGroup.Id;
					scaffold.UploaderId = userId;
					scaffold.ScaffoldTags = autogeneratedTags.ToList();
					scaffoldGroup.Scaffolds.Add(scaffold);
				}

				scaffoldGroup.UpdatedAt = DateTime.UtcNow;
				await _context.SaveChangesAsync();

				var refreshedGroup = await _scaffoldGroupRepository.Get(scaffoldGroupId);
				if (refreshedGroup == null)
					return (false, "ScaffoldGroupNotFound", null);

				var images = await _scaffoldGroupRepository.GetScaffoldGroupImages(scaffoldGroupId);
				var tagNames = autogeneratedTags.Select(tag => tag.Tag.Name).ToList();
				var scaffoldGroupToReturn = _modelMapper.MapToScaffoldGroupSummaryDto(refreshedGroup, images, tagNames, userId);

				return (true, "", scaffoldGroupToReturn);
			}
			catch (ArgumentException ex)
			{
				_logger.LogWarning(ex, "Invalid scaffold append payload for scaffold group {ScaffoldGroupId}", scaffoldGroupId);
				return (false, ex.Message, null);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to append scaffolds to scaffold group {ScaffoldGroupId}", scaffoldGroupId);
				return (false, "UnexpectedError", null);
			}
		}

		private static void NormalizeInputGroup(ScaffoldGroupToCreateDto dto)
		{
			if (dto.InputGroup == null)
				throw new ArgumentException("InputGroup is required.");

			if (!dto.InputGroup.ContainerSize.HasValue &&
				TryCalculateContainerVolume(dto.InputGroup.ContainerDimensions, out var volume))
			{
				dto.InputGroup.ContainerSize = volume;
			}
		}

		private static void EnsureSizeDistribution(ScaffoldGroupToCreateDto dto)
		{
			if (dto.InputGroup == null)
				throw new ArgumentException("InputGroup is required.");

			var inputArray = TryReadNumberArray(dto.InputGroup.SizeDistribution?.RootElement);
			var particleDiamArray = GetParticleDiamValues(dto);

			var hasInput = inputArray != null && inputArray.Count > 0;
			var hasParticleDiam = particleDiamArray != null && particleDiamArray.Count > 0;

			if (!hasInput)
			{
				if (!hasParticleDiam)
					throw new ArgumentException("sizeDistribution is missing and could not be derived from OtherDescriptor 'ParticleDiam'.");

				dto.InputGroup.SizeDistribution = ToJsonArrayDocument(particleDiamArray!);
				return;
			}

			if (!hasParticleDiam)
				return;

			if (inputArray!.Count != particleDiamArray!.Count)
			{
				throw new ArgumentException("inputGroup.sizeDistribution does not match OtherDescriptor 'ParticleDiam' (different lengths).");
			}

			for (int i = 0; i < inputArray.Count; i++)
			{
				var a = inputArray[i];
				var b = particleDiamArray[i];
				if (Math.Abs(a - b) > 1e-8)
				{
					throw new ArgumentException("inputGroup.sizeDistribution does not match OtherDescriptor 'ParticleDiam'.");
				}
			}
		}

		private static void NormalizeParticleProperties(ScaffoldGroupToCreateDto dto)
		{
			if (dto.InputGroup?.ParticlePropertyGroups == null || dto.InputGroup.ParticlePropertyGroups.Count == 0)
				return;

			var distribution = TryReadNumberArray(dto.InputGroup.SizeDistribution?.RootElement);
			var canDeriveStats = distribution is { Count: > 0 };

			if (dto.InputGroup.ParticlePropertyGroups.Count > 1 &&
				dto.InputGroup.ParticlePropertyGroups.Any(p => IsMissingMean(p.MeanSize) || IsMissingStdDev(p.StandardDeviationSize)))
			{
				throw new ArgumentException("Cannot derive particle mean/std from a shared sizeDistribution when multiple particlePropertyGroups are present.");
			}

			var derivedMean = canDeriveStats ? distribution!.Average() : 0;
			var derivedStdDev = canDeriveStats ? CalculatePopulationStdDev(distribution!, derivedMean) : 0;

			foreach (var particle in dto.InputGroup.ParticlePropertyGroups)
			{
				if (!dto.IsSimulated)
				{
					if (IsBlankOrPlaceholder(particle.Dispersity, treatUnknownAsMissing: false))
						particle.Dispersity = "polydisperse";

					if (IsBlankOrPlaceholder(particle.SizeDistributionType, treatUnknownAsMissing: false))
						particle.SizeDistributionType = "unknown";
				}

				if (IsMissingMean(particle.MeanSize))
				{
					if (!canDeriveStats)
						throw new ArgumentException("meanSize is missing and could not be derived from inputGroup.sizeDistribution.");

					particle.MeanSize = derivedMean;
				}

				if (IsMissingStdDev(particle.StandardDeviationSize))
				{
					if (!canDeriveStats)
						throw new ArgumentException("standardDeviationSize is missing and could not be derived from inputGroup.sizeDistribution.");

					particle.StandardDeviationSize = derivedStdDev;
				}
			}
		}

		private static List<double>? GetParticleDiamValues(ScaffoldGroupToCreateDto dto)
		{
			foreach (var scaffold in dto.Scaffolds ?? [])
			{
				var particleDiam = scaffold.OtherDescriptors?
					.FirstOrDefault(d => string.Equals(d.Name, "ParticleDiam", StringComparison.OrdinalIgnoreCase));

				if (particleDiam?.Values == null)
					continue;

				var parsed = TryReadNumberArray(particleDiam.Values.RootElement);
				if (parsed is { Count: > 0 })
					return parsed;
			}

			return null;
		}

		private static List<double>? TryReadNumberArray(JsonElement? root)
		{
			if (root == null || root.Value.ValueKind == JsonValueKind.Undefined || root.Value.ValueKind == JsonValueKind.Null)
				return null;

			if (root.Value.ValueKind != JsonValueKind.Array)
				return null;

			var values = new List<double>();
			foreach (var item in root.Value.EnumerateArray())
			{
				switch (item.ValueKind)
				{
					case JsonValueKind.Number:
						values.Add(item.GetDouble());
						break;
					case JsonValueKind.String:
						var str = item.GetString();
						if (string.IsNullOrWhiteSpace(str))
							return null;
						if (!double.TryParse(str, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed))
							return null;
						values.Add(parsed);
						break;
					default:
						return null;
				}
			}

			return values;
		}

		private static JsonDocument ToJsonArrayDocument(List<double> values)
		{
			var json = JsonSerializer.Serialize(values);
			return JsonDocument.Parse(json);
		}

		private static bool TryCalculateContainerVolume(string? containerDimensions, out int volume)
		{
			volume = 0;

			if (string.IsNullOrWhiteSpace(containerDimensions))
				return false;

			var parts = System.Text.RegularExpressions.Regex.Split(containerDimensions.Trim(), @"\s*[x×]\s*")
				.Where(part => !string.IsNullOrWhiteSpace(part))
				.ToArray();

			if (parts.Length == 0)
				return false;

			double product = 1;
			foreach (var part in parts)
			{
				if (!double.TryParse(part, NumberStyles.Float, CultureInfo.InvariantCulture, out var dimension) || dimension <= 0)
					return false;

				product *= dimension;
			}

			volume = (int)Math.Round(product, MidpointRounding.AwayFromZero);
			return true;
		}

		private static bool IsBlankOrPlaceholder(string? value, bool treatUnknownAsMissing = true)
		{
			if (string.IsNullOrWhiteSpace(value))
				return true;

			var trimmed = value.Trim();
			return (trimmed.Contains('<') && trimmed.Contains('>')) ||
				(treatUnknownAsMissing && string.Equals(trimmed, "unknown", StringComparison.OrdinalIgnoreCase)) ||
				string.Equals(trimmed, "n/a", StringComparison.OrdinalIgnoreCase);
		}

		private static bool IsMissingMean(double value)
		{
			return double.IsNaN(value) || double.IsInfinity(value) || value <= 0;
		}

		private static bool IsMissingStdDev(double value)
		{
			return double.IsNaN(value) || double.IsInfinity(value) || value <= 0;
		}

		private bool AreInputGroupsCompatible(InputGroup existing, InputGroupToCreateDto incoming)
		{
			var incomingPacking = _metadataService.ParsePackingConfiguration(incoming.PackingConfiguration);

			if (!string.Equals(existing.ContainerShape ?? "", incoming.ContainerShape ?? "", StringComparison.OrdinalIgnoreCase))
				return false;

			if (existing.PackingConfiguration != incomingPacking)
				return false;

			var existingParticles = existing.ParticlePropertyGroups
				.Select((p, index) => new
				{
					Shape = p.Shape ?? "",
					Stiffness = p.Stiffness ?? "",
					Index = index
				});

			var incomingParticles = incoming.ParticlePropertyGroups
				.Select((p, index) => new
				{
					Shape = p.Shape ?? "",
					Stiffness = p.Stiffness ?? "",
					Index = index
				});

			return JsonSerializer.Serialize(existingParticles) == JsonSerializer.Serialize(incomingParticles);
		}

		private static double CalculatePopulationStdDev(List<double> values, double mean)
		{
			if (values.Count == 0)
				return 0;

			var variance = values.Sum(value => Math.Pow(value - mean, 2)) / values.Count;
			return Math.Sqrt(variance);
		}

		public async Task<(bool Succeeded, string ErrorMessage, IEnumerable<ScaffoldGroupBaseDto>? CreatedScaffoldGroups)>
			CreateScaffoldGroupsFromJsonStream(
				Stream jsonStream,
				string userId,
				int batchSize = 50,
				CancellationToken ct = default)
		{
			try
			{
				var opts = new JsonSerializerOptions
				{
					PropertyNameCaseInsensitive = true,
					DefaultBufferSize = 1 << 20, // 1MB buffer; tune as needed
					NumberHandling = JsonNumberHandling.AllowReadingFromString
				};

				var createdAll = new List<ScaffoldGroupBaseDto>(capacity: batchSize * 2);
				var buffer = new List<ScaffoldGroupToCreateDto>(capacity: batchSize);

				// Expecting a top-level JSON array of ScaffoldGroupToCreateDto
				await foreach (var dto in JsonSerializer.DeserializeAsyncEnumerable<ScaffoldGroupToCreateDto>(jsonStream, opts, ct))
				{
					ct.ThrowIfCancellationRequested();
					if (dto is null) continue; // can occur between tokens/whitespace

					buffer.Add(dto);

					if (buffer.Count >= batchSize)
					{
						var (ok, err, createdBatch) = await CreateScaffoldGroups(buffer, userId);
						if (!ok)
							return (false, err, null);

						if (createdBatch != null)
							createdAll.AddRange(createdBatch);

						buffer.Clear();
					}
				}

				// flush remaining
				if (buffer.Count > 0)
				{
					var (ok, err, createdBatch) = await CreateScaffoldGroups(buffer, userId);
					if (!ok)
						return (false, err, null);

					if (createdBatch != null)
						createdAll.AddRange(createdBatch);
				}

				return (true, string.Empty, createdAll);
			}
			catch (JsonException jex)
			{
				_logger.LogError(jex, "Invalid JSON in streamed scaffold group upload");
				return (false, "InvalidJson", null);
			}
			catch (OperationCanceledException)
			{
				return (false, "Canceled", null);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to create scaffold groups from streamed JSON");
				return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, BatchOperationResult? result)> ResetNamesAndComments(List<int> ids)
		{
			if (ids == null || ids.Count == 0)
			{
				return (false, "No scaffold group IDs provided", null);
			}

			var scaffoldGroups = await _scaffoldGroupRepository.GetWithInputDataByIds(ids);
			var result = new BatchOperationResult();

			foreach (var group in scaffoldGroups)
			{
				try
				{
					_metadataService.SetScaffoldGroupNameAndComments(group);

					result.SucceededIds.Add(group.Id);
				}
				catch (Exception ex)
				{
					_logger.LogError(ex, $"Error updating title & comments for scaffold group {group.Id}");
					result.FailedIds.Add(group.Id);
					return (false, $"Error updating title & comments for scaffold group {group.Id}", result);
				}

			}

			try
			{
				await _context.SaveChangesAsync();
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Error saving updated scaffold group names/comments");
				return (false, "Error saving updated scaffold group names/comments", result);
			}

			return (true, "", result);
		}

		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupBaseDto? scaffoldGroup)> GetScaffoldGroup(int id, string userId, int? numReplicates)
		{
			try
			{
				// ScaffoldGroup? scaffoldGroup = await _scaffoldGroupRepository.Get(id); 
				var scaffoldGroup  = await _scaffoldGroupRepository.GetSummary(id);

				if (scaffoldGroup == null)
				{
					return (false, "NotFound", null);
				}
				if (scaffoldGroup.IsPublic == false && scaffoldGroup.UploaderId != userId)
				{
					return (false, "Unauthorized", null);
				}

				var (succeeded, errorMessage, completeScaffoldGroups) = 
					await GetCompleteScaffoldGroupsFromSummaries([scaffoldGroup], userId, isDetailed: true, filter: null);

				if (!succeeded || completeScaffoldGroups == null)
				{
					return (false, errorMessage, null);
				}

				return (true, "", completeScaffoldGroups.First());

			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to get scaffold group {id}", id);
        		return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupSummaryDto? scaffoldGroup)> GetScaffoldGroupSummaryByScaffoldId(int scaffoldId, string userId)
		{
			try
			{
				// ScaffoldGroup? scaffoldGroup = await _scaffoldGroupRepository.Get(id); 
				var scaffoldGroup  = await _scaffoldGroupRepository.GetSummaryByScaffoldId(scaffoldId);

				if (scaffoldGroup == null)
				{
					return (false, "NotFound", null);
				}
				if (scaffoldGroup.IsPublic == false && scaffoldGroup.UploaderId != userId)
				{
					return (false, "Unauthorized", null);
				}

				return (true, "", scaffoldGroup);

			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to get scaffold group {scaffoldId}", scaffoldId);
        		return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupSummaryDto? scaffoldGroup)> GetScaffoldGroupSummary(int id, string userId)
		{
			try
			{
				// ScaffoldGroup? scaffoldGroup = await _scaffoldGroupRepository.Get(id); 
				var scaffoldGroup  = await _scaffoldGroupRepository.GetSummary(id);

				if (scaffoldGroup == null)
				{
					return (false, "NotFound", null);
				}
				if (scaffoldGroup.IsPublic == false && scaffoldGroup.UploaderId != userId)
				{
					return (false, "Unauthorized", null);
				}

				return (true, "", scaffoldGroup);

			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to get scaffold group {id}", id);
        		return (false, "UnexpectedError", null);
			}
		}
		
		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupDataDto? Result)> GetDataForVisualization(int scaffoldGroupId, string? userId,  List<int> descriptorTypeIds)
		{
			try
			{
				var summary = await _scaffoldGroupRepository.GetSummary(scaffoldGroupId);
				if (summary == null) return (false, "Scaffold group not found", null);

				var (poreInfoSucceeded, poreInfoErrorMesssage, poreData) = await _descriptorService.GetPoreDescriptorInfoScaffoldGroup(scaffoldGroupId, descriptorTypeIds);
				if (!poreInfoSucceeded || poreData == null) return (false, poreInfoErrorMesssage, null);

				if (string.IsNullOrEmpty(userId))
				{
					var user = await _userAuthHelper.GetFirstUserByRoleAsync("administrator");
					userId = user!.Id;
				}

				var (succeededScaffoldGroups, errorMessageScaffoldGroup, completeScaffoldGroups) = 
					await GetCompleteScaffoldGroupsFromSummaries([summary], userId, isDetailed: false, filter: null);

				if (!succeededScaffoldGroups || completeScaffoldGroups == null) return (false, errorMessageScaffoldGroup, null);

				var completeScaffoldGroup = completeScaffoldGroups.FirstOrDefault();

				var dto = new ScaffoldGroupDataDto
				{
					ScaffoldGroupId = scaffoldGroupId,
					ScaffoldGroup = completeScaffoldGroup!,
					PoreDescriptors = poreData.Scaffolds
				};

				return (true, "", dto);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to load scaffold group data");
				return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, IEnumerable<ScaffoldGroupBaseDto>? scaffoldGroups)>
			GetFilteredScaffoldGroups(ScaffoldFilter filter, string userId, bool isDetailed = false)
		{
			try
			{
				// Ensure we have a valid user
				if (string.IsNullOrEmpty(userId))
				{
					var user = await _userAuthHelper.GetFirstUserByRoleAsync("administrator");
					userId = user!.Id;
					isDetailed = false;
				}

				if (filter.TagNames?.Count > 0)
				{
					var tagIdsFromNames = await _tagService.GetAutogeneratedTagIdsFromNames(filter.TagNames);
					filter.TagIds = (filter.TagIds ?? new List<int>()).Union(tagIdsFromNames).ToList();
				}

				// Fetch scaffold groups with necessary fields
				var scaffoldGroups = await _scaffoldGroupRepository.GetFilteredScaffoldGroupSummaries(filter, userId);

				// if (scaffoldGroups == null || !scaffoldGroups.Any())
				// {
				// 	return (false, "NotFound", null);
				// }

				return await GetCompleteScaffoldGroupsFromSummaries(scaffoldGroups ?? [], userId, isDetailed, filter);

			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to get filtered scaffold groups");
				return (false, "UnexpectedError", null);
			}
		}

		private async Task<(bool Succeeded, string ErrorMessage, IEnumerable<ScaffoldGroupBaseDto>? scaffoldGroups)> GetCompleteScaffoldGroupsFromSummaries(IEnumerable<ScaffoldGroupSummaryDto> scaffoldGroups, string userId, bool isDetailed, ScaffoldFilter? filter)
		{
			try
			{
				var scaffoldGroupIds = scaffoldGroups.Select(sg => sg.Id).ToList();

				var imagesLookup = isDetailed
						? await _imageService.GetAllImagesForScaffoldGroups(scaffoldGroupIds)
						: await _imageService.GetThumbnailsForScaffoldGroups(scaffoldGroupIds);
				var tagsLookup = await _tagService.GetTagNamesForScaffoldGroups(scaffoldGroupIds, userId);

				Dictionary<int, List<ScaffoldBaseDto>> scaffoldLookup = [];

				if (isDetailed)
				{
					var scaffoldIds = scaffoldGroups
						.SelectMany(sg => sg.ScaffoldIds)
						.ToList();					
					
					var scaffolds = await _descriptorService.GetScaffoldsWithDescriptorsFromScaffoldIds(scaffoldIds, filter);
					scaffoldLookup = scaffolds
						.GroupBy(s => scaffoldGroups.First(sg => sg.ScaffoldIds.Contains(s.Id)).Id)
						.ToDictionary(g => g.Key, g => g.ToList());
				}

				var scaffoldGroupDtos = scaffoldGroups.Select<ScaffoldGroupSummaryDto, ScaffoldGroupBaseDto>(sg =>
				{
					// Assign images and tags once
					sg.Images = imagesLookup.ContainsKey(sg.Id) ? imagesLookup[sg.Id] : [];
					sg.Tags = tagsLookup.ContainsKey(sg.Id) ? tagsLookup[sg.Id] : [];

					// If isDetailed == false, return sg as it is (remains ScaffoldGroupSummaryDto)
					if (!isDetailed) return sg;

					// Create and return ScaffoldGroupDetailedDto
					return new ScaffoldGroupDetailedDto
					{
						Id = sg.Id,
						Name = sg.Name,
						CreatedAt = sg.CreatedAt,
						UploaderId = sg.UploaderId,
						IsPublic = sg.IsPublic,
						IsSimulated = sg.IsSimulated,
						Tags = sg.Tags,
						NumReplicates = sg.NumReplicates,
						Images = sg.Images,
						Inputs = sg.Inputs,
						ScaffoldIds = sg.ScaffoldIds,
						ScaffoldIdsWithDomains = sg.ScaffoldIdsWithDomains,
						Scaffolds = scaffoldLookup.ContainsKey(sg.Id) ? scaffoldLookup[sg.Id] : []
					};
				}).ToList();

				return (true, "", scaffoldGroupDtos);

			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to get filtered scaffold groups");
				return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupSummaryDto? UpdatedScaffoldGroup)> DeleteScaffold(int scaffoldId, string userId)
		{
			try
			{
				var scaffold = await _context.Scaffolds
					.Include(s => s.Images)
					.Include(s => s.Domains)
					.Include(s => s.ScaffoldGroup)
						.ThenInclude(sg => sg.Scaffolds)
					.FirstOrDefaultAsync(s => s.Id == scaffoldId);

				if (scaffold == null)
					return (false, "ScaffoldNotFound", null);

				var isAdmin = await _userAuthHelper.IsInRole(userId, "administrator");
				if (scaffold.ScaffoldGroup.UploaderId != userId && scaffold.UploaderId != userId && !isAdmin)
					return (false, "Unauthorized", null);

				if (scaffold.Images.Any())
				{
					var imageIds = scaffold.Images.Select(img => img.Id).Distinct();
					var (imgSucceeded, failedImageIds) = await _imageService.DeleteImages(imageIds, userId);
					if (!imgSucceeded)
						return (false, $"Failed to delete some images from Cloudinary: {string.Join(", ", failedImageIds)}", null);
				}

				foreach (var domain in scaffold.Domains.ToList())
				{
					var (success, error) = await _domainService.DeleteDomain(domain.Id, userId);
					if (!success)
						return (false, $"Failed to delete domain ID {domain.Id}: {error}", null);
				}

				var scaffoldGroupId = scaffold.ScaffoldGroupId;
				_context.Scaffolds.Remove(scaffold);
				await _context.SaveChangesAsync();

				var summary = await _scaffoldGroupRepository.GetSummary(scaffoldGroupId);
				return summary == null
					? (false, "ScaffoldGroupNotFound", null)
					: (true, "", summary);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Error deleting scaffold {ScaffoldId}", scaffoldId);
				return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage)> DeleteScaffoldGroup(int scaffoldGroupId, string userId)
		{
			try
			{
				var scaffoldGroup = await _scaffoldGroupRepository.Get(scaffoldGroupId);
				if (scaffoldGroup == null)
					return (false, "Scaffold group not found.");

				// Authorization check: must be uploader or admin
				var isAdmin = await _userAuthHelper.IsInRole(userId, "administrator");

				if (scaffoldGroup.UploaderId != userId && !isAdmin)
					return (false, "Unauthorized to delete this scaffold group.");

				// 1. Gather all image IDs (group-level + scaffold-level)
				var imageIds = scaffoldGroup.Images.Select(img => img.Id).ToList();

				foreach (var scaffold in scaffoldGroup.Scaffolds)
				{
					imageIds.AddRange(scaffold.Images.Select(img => img.Id));
				}

				if (imageIds.Any())
				{
					var (imgSucceeded, failedImageIds) = await _imageService.DeleteImages(imageIds.Distinct(), userId);
					if (!imgSucceeded)
					{
						return (false, $"Failed to delete some images from Cloudinary: {string.Join(", ", failedImageIds)}");
					}
				}

				// 2. Delete all mesh files from disk
				var domainsWithFiles = scaffoldGroup.Scaffolds
					.SelectMany(s => s.Domains)
					.ToList();

				foreach (var domain in domainsWithFiles)
				{
					var (success, error) = await _domainService.DeleteDomain(domain.Id, userId);
					if (!success)
					{
						return (false, $"Failed to delete domain ID {domain.Id}: {error}");
					}
				}
				// 3. Remove the scaffold group (EF cascade will clean up child entities)
				_scaffoldGroupRepository.Delete(scaffoldGroup);
				await _context.SaveChangesAsync(); // call SaveChanges from your repository

				return (true, "");
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Error deleting scaffold group {ScaffoldGroupId}", scaffoldGroupId);
				return (false, "Unexpected error occurred while deleting the scaffold group.");
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, ICollection<ImageToShowDto>? scaffoldGroupImages)> GetScaffoldGroupImages(int scaffoldGroupId)
		{
			try
			{
				var images = await _scaffoldGroupRepository.GetScaffoldGroupImages(scaffoldGroupId);
				var imagesToReturn = images.Select(_modelMapper.MapImageToDto).ToList();
				return (true, "", imagesToReturn);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to get scaffold group images");
        		return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupSummaryDto? updatedScaffoldGroup)> UpdateScaffoldGroupImage(string userId, int scaffoldGroupId, ImageToUpdateDto image)
		{
			try
			{
				var scaffoldGroup = await _scaffoldGroupRepository.Get(scaffoldGroupId);

				if (scaffoldGroup == null) return (false, "ScaffoldGroup not found", null);

				if (scaffoldGroup.UploaderId != userId) return (false, "Unauthorized", null);

				var updatedImage = await _imageService.UpdateImage(image, scaffoldGroup);

				if (updatedImage == null) return (false, "Image not found", null);

				var updatedScaffoldGroup = await _scaffoldGroupRepository.Get(scaffoldGroupId);
				var images = await _scaffoldGroupRepository.GetScaffoldGroupImages(scaffoldGroupId);
				var scaffoldGroupToReturn = _modelMapper.MapToScaffoldGroupSummaryDto(updatedScaffoldGroup!, images, [], userId);

				return (true, "", scaffoldGroupToReturn);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to update scaffold group image");
        		return (false, "UnexpectedError", null);
			}
		}

		public async Task<List<ScaffoldMissingThumbnailInfoDto>> GetScaffoldsMissingThumbnailsByCategory(ImageCategory imageCategory = ImageCategory.Particles, int? scaffoldGroupId = null)
		{
			try
			{
				var scaffolds = await _scaffoldGroupRepository.GetScaffoldsMissingThumbnailsByCategory(imageCategory, scaffoldGroupId);
				return scaffolds;
			}
			catch (Exception ex)
			{

				_logger.LogError(ex, "Error getting thumbnails");
				return [];
			}
		}

		public async Task<ThumbnailResetPreviewDto> GetThumbnailResetPreview(ImageCategory imageCategory, int? scaffoldGroupId = null)
		{
			try
			{
				var thumbnails = await _imageService.GetThumbnailsWithScaffoldGroupByCategory(imageCategory, scaffoldGroupId);
				var scaffoldGroupsWithMesh = await _scaffoldGroupRepository.GetScaffoldGroupIdsWithMeshForCategory(imageCategory, scaffoldGroupId);

				var meshSet = scaffoldGroupsWithMesh.ToHashSet();
				var thumbnailGroupIds = thumbnails.Select(t => t.ScaffoldGroupId).Distinct().ToList();
				var orphanedIds = thumbnailGroupIds.Where(id => !meshSet.Contains(id)).Distinct().ToList();

				return new ThumbnailResetPreviewDto
				{
					ImageIdsToDelete = thumbnails.Select(t => t.ImageId).ToList(),
					ScaffoldsWithMeshIds = scaffoldGroupsWithMesh,
					OrphanedScaffoldIds = orphanedIds
				};
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Error computing thumbnail reset preview");
				return new ThumbnailResetPreviewDto();
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, ScaffoldGroupBaseDto? scaffoldGroup)> GetScaffoldGroupPreview(int id, int maxReplicates = 3)
		{
			try
			{
				var scaffoldGroup = await _scaffoldGroupRepository.GetSummary(id);

				if (scaffoldGroup == null)
				{
					return (false, "NotFound", null);
				}
				if (!scaffoldGroup.IsPublic)
				{
					return (false, "Unauthorized", null);
				}

				// Limit to first N replicates
				scaffoldGroup.ScaffoldIds = scaffoldGroup.ScaffoldIds.Take(maxReplicates).ToList();

				var (succeeded, errorMessage, completeScaffoldGroups) =
					await GetCompleteScaffoldGroupsFromSummaries([scaffoldGroup], "0", isDetailed: true, filter: null);

				if (!succeeded || completeScaffoldGroups == null)
				{
					return (false, errorMessage, null);
				}

				return (true, "", completeScaffoldGroups.First());
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to get scaffold group preview {id}", id);
				return (false, "UnexpectedError", null);
			}
		}

		public async Task<(bool Succeeded, string ErrorMessage, List<ScaffoldGroupMatch>? scaffoldGroupMatches)> FindPotentialMatches(
			InputGroupForMatchRequest request,
			string userId,
			int topN = 5)
		{
			try
			{
				// For experimental scaffolds, return empty - always create new
				if (!request.IsSimulated)
					return (true, "", new List<ScaffoldGroupMatch>());

				// Build filter from request
				var filter = new ScaffoldFilter
				{
					UserId = userId,
					ParticleSizes = request.Particles
						.Select(p => (int)p.MeanSize)
						.Distinct()
						.ToList()
				};

				// Get potential candidates
				var candidates = await _scaffoldGroupRepository.GetFilteredScaffoldGroupSummaries(filter, userId);

				if (candidates == null) return (true, "No matches found", new List<ScaffoldGroupMatch>());

				// Score each candidate
				var matches = candidates
					.Select(sg => new ScaffoldGroupMatch
					{
						ScaffoldGroupId = sg.Id,
						Name = sg.Name ?? "N/A",
						MatchScore = CalculateMatchScore(request, sg, out var differences),
						Differences = differences,
						Details = sg
					})
					.Where(m => m.MatchScore >= 70) // Threshold for "good enough"
					.OrderByDescending(m => m.MatchScore)
					.Take(topN)
					.ToList();

				return (true, "", matches);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Failed to get candidate matches");
        		return (false, "UnexpectedError", null);
			}
			
		}

		private double CalculateMatchScore(
			InputGroupForMatchRequest request,
			ScaffoldGroupSummaryDto candidate,
			out Dictionary<string, string> differences)
		{
			differences = new Dictionary<string, string>();
			double score = 100.0;

			// Container shape (critical - major penalty)
			if (candidate?.Inputs?.ContainerShape != request.ContainerShape)
			{
				score -= 30;
				differences["ContainerShape"] = $"{candidate?.Inputs?.ContainerShape ?? "None"} vs {request.ContainerShape ?? "None"}";
			}

			// Container size (allow small tolerance)
			if (candidate?.Inputs?.ContainerSize.HasValue == true && request.ContainerSize.HasValue)
			{
				var sizeDiff = Math.Abs(candidate.Inputs.ContainerSize.Value - request.ContainerSize.Value);
				if (sizeDiff > 0.01)
				{
					score -= Math.Min(20, sizeDiff * 10);
					differences["ContainerSize"] = $"{candidate.Inputs.ContainerSize} vs {request.ContainerSize}";
				}
			}
			else if (candidate?.Inputs?.ContainerSize.HasValue != request.ContainerSize.HasValue)
			{
				// One has a value, the other doesn't
				score -= 15;
				differences["ContainerSize"] = $"{candidate?.Inputs?.ContainerSize?.ToString() ?? "Not specified"} vs {request.ContainerSize?.ToString() ?? "Not specified"}";
			}

			// Packing configuration
			var candidatePackingConfig = candidate?.Inputs?.PackingConfiguration?.ToString();
			if (candidatePackingConfig != request.PackingConfiguration)
			{
				score -= 20;
				differences["PackingConfiguration"] = $"{candidatePackingConfig ?? "None"} vs {request.PackingConfiguration ?? "None"}";
			}

			// Compare particles (this gets more complex)
			score -= CompareParticleProperties(request.Particles, candidate?.Inputs?.Particles ?? new List<ParticlePropertyBaseDto>(), differences);

			return Math.Max(0, score);
		}
		
		private double CompareParticleProperties(
			IEnumerable<ParticlePropertyGroupToCreateDto> requestParticles,
			IEnumerable<ParticlePropertyBaseDto> candidateParticles,
			Dictionary<string, string> differences)
		{
			double penalty = 0.0;

			var candidateParticlesList = candidateParticles.ToList();
			var requestedParticlesList = requestParticles.ToList();

			// Check if particle counts match
			if (requestedParticlesList.Count != candidateParticlesList.Count)
			{
				penalty += 15;
				differences["ParticleCount"] = $"{candidateParticlesList.Count} particle types vs {requestedParticlesList.Count} particle types";
				// If counts differ significantly, return early with heavy penalty
				if (Math.Abs(requestedParticlesList.Count - candidateParticlesList.Count) > 1)
					return penalty + 20;
			}

			// Sort both lists by MeanSize for consistent comparison
			var sortedRequest = requestParticles.OrderBy(p => p.MeanSize).ToList();
			var sortedCandidate = candidateParticlesList.OrderBy(p => p.MeanSize).ToList();

			// Compare each particle type
			int comparisonCount = Math.Min(sortedRequest.Count, sortedCandidate.Count);
			for (int i = 0; i < comparisonCount; i++)
			{
				var reqParticle = sortedRequest[i];
				var candParticle = sortedCandidate[i];

				// Shape comparison (critical)
				if (reqParticle.Shape != candParticle.Shape)
				{
					penalty += 10;
					differences[$"Particle{i + 1}_Shape"] = $"{candParticle.Shape} vs {reqParticle.Shape}";
				}

				// Stiffness comparison
				if (reqParticle.Stiffness != candParticle.Stiffness)
				{
					penalty += 5;
					differences[$"Particle{i + 1}_Stiffness"] = $"{candParticle.Stiffness} vs {reqParticle.Stiffness}";
				}

				// Dispersity comparison
				if (reqParticle.Dispersity != candParticle.Dispersity)
				{
					penalty += 5;
					differences[$"Particle{i + 1}_Dispersity"] = $"{candParticle.Dispersity} vs {reqParticle.Dispersity}";
				}

				// Mean size comparison (allow small tolerance)
				var sizeDiff = Math.Abs(reqParticle.MeanSize - candParticle.MeanSize);
				if (sizeDiff > 1.0) // More than 1 unit difference
				{
					penalty += Math.Min(8, sizeDiff * 0.5);
					differences[$"Particle{i + 1}_MeanSize"] = $"{candParticle.MeanSize:F2} vs {reqParticle.MeanSize:F2}";
				}

				// Standard deviation comparison (if both specified)
				if (reqParticle.StandardDeviationSize > 0 && candParticle.StandardDeviationSize.HasValue)
				{
					var stdDevDiff = Math.Abs(reqParticle.StandardDeviationSize - candParticle.StandardDeviationSize.Value);
					if (stdDevDiff > 0.5)
					{
						penalty += Math.Min(5, stdDevDiff);
						differences[$"Particle{i + 1}_StdDev"] = $"{candParticle.StandardDeviationSize:F2} vs {reqParticle.StandardDeviationSize:F2}";
					}
				}

				if (reqParticle.Proportion > 0 && candParticle.Proportion.HasValue)
				{
					// Proportion comparison
					var propDiff = Math.Abs(reqParticle.Proportion - candParticle.Proportion.Value);
					if (propDiff > 0.05) // More than 5% difference
					{
						penalty += Math.Min(5, propDiff * 20);
						differences[$"Particle{i + 1}_Proportion"] = $"{candParticle.Proportion:P0} vs {reqParticle.Proportion:P0}";
					}
				}

				
			}

			return penalty;
		}


	}
}
