
namespace Data.Models
{
	public class Tag
	{
		public int Id { get; set; }
		public string Name { get; set; } = null!;
		public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
		public bool IsAutoGenerated { get; set; } = false;
		public string? ReferenceProperty { get; set; } = "other";
		public ICollection<ScaffoldTag> ScaffoldTags { get; set; } = [];
	
	}
}
