import { makeAutoObservable, runInAction } from "mobx";
import agent from "../api/agent";
import { User, UserLogin, UserRegister } from "../models/user";
import history from "../helpers/History";
import { store } from "./store";
import { Tag } from "../models/tag";

export default class ResourceStore {
	tags: Tag[] | null = null;

	constructor() {
		makeAutoObservable(this)
	}

	getAutogeneratedTags = async () => {
		try {
			const response = await agent.Resources.getAutogeneratedTags();
			return response.data;
			// runInAction(() => {
			// 	this.tags = response.data
			// 	return response.data
			// })
		} catch (error) {
			console.error(error)
		}
	}


	
}