import { makeAutoObservable } from "mobx";
import agent from "../api/agent";
import { Tag } from "../models/tag";

export default class ResourceStore {
	tags: Tag[] | null = null;

	constructor() {
		makeAutoObservable(this)
	}

	getAutogeneratedTags = async () => {
		try {
			const response = await agent.Resources.getAutogeneratedTags();
			return response.data;
			// runInAction(() => {
			// 	this.tags = response.data
			// 	return response.data
			// })
		} catch (error) {
			console.error(error)
		}
	}

	getDescriptorTypes = async () => {
		try {
			const response = await agent.Resources.getDescriptorTypes();
			return response.data;
		} catch (error) {
			console.error(error)
		}
	}


	
}