using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Data.Data
{
    /// <inheritdoc />
    public partial class IsAutoGeneratedToTag : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Tags",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Tags");
        }
    }
}
