using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Data.Migrations
{
    /// <inheritdoc />
    public partial class NormalizeStiffnessTagsAndAddStiff : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Normalize "semi-soft" → "semisoft" in Tags
            migrationBuilder.Sql(
                "UPDATE \"Tags\" SET \"Name\" = 'semisoft' WHERE \"Name\" = 'semi-soft' AND \"ReferenceProperty\" = 'stiffness'");

            // Normalize "semi-soft" → "semisoft" in ParticlePropertyGroups
            migrationBuilder.Sql(
                "UPDATE \"ParticlePropertyGroups\" SET \"Stiffness\" = 'semisoft' WHERE \"Stiffness\" = 'semi-soft'");

            // Add "stiff" tag if missing
            migrationBuilder.Sql(
                "INSERT INTO \"Tags\" (\"Name\", \"ReferenceProperty\", \"IsAutoGenerated\", \"CreatedAt\") " +
                "SELECT 'stiff', 'stiffness', true, NOW() " +
                "WHERE NOT EXISTS (SELECT 1 FROM \"Tags\" WHERE \"Name\" = 'stiff')");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
