using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Data.Migrations
{
    /// <inheritdoc />
    public partial class AddYoungsModulusToParticlePropertyGroup : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<double>(
                name: "YoungsModulus",
                table: "ParticlePropertyGroups",
                type: "double precision",
                nullable: true);

            // Normalize "semi-soft" → "semisoft" in both Tags and ParticlePropertyGroups
            migrationBuilder.Sql(
                "UPDATE \"Tags\" SET \"Name\" = 'semisoft' WHERE \"Name\" = 'semi-soft' AND \"ReferenceProperty\" = 'stiffness'");
            migrationBuilder.Sql(
                "UPDATE \"ParticlePropertyGroups\" SET \"Stiffness\" = 'semisoft' WHERE \"Stiffness\" = 'semi-soft'");

            // Backfill known values from paper:
            // semisoft (λ=1000, μ=250) → E = 700 Pa
            migrationBuilder.Sql(
                "UPDATE \"ParticlePropertyGroups\" SET \"YoungsModulus\" = 700 WHERE \"Stiffness\" = 'semisoft'");

            // soft (λ=400, μ=50) → E ≈ 144.4 Pa
            migrationBuilder.Sql(
                "UPDATE \"ParticlePropertyGroups\" SET \"YoungsModulus\" = 144.4 WHERE \"Stiffness\" = 'soft'");

            // rigid → stays null (non-deformable, no E)

            // Seed "stiff" tag for existing databases
            migrationBuilder.Sql(
                "INSERT INTO \"Tags\" (\"Name\", \"ReferenceProperty\", \"IsAutoGenerated\", \"CreatedAt\") " +
                "SELECT 'stiff', 'stiffness', true, NOW() " +
                "WHERE NOT EXISTS (SELECT 1 FROM \"Tags\" WHERE \"Name\" = 'stiff')");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "YoungsModulus",
                table: "ParticlePropertyGroups");
        }
    }
}
