
namespace Infrastructure.DTOs
{
	public class TagToSeedDto
	{
		public string Name { get; set; } = null!;
		public string ReferenceProperty { get; set; } = null!;
		public bool IsAutoGenerated { get; set; } = true;
	}
}